# Generated by Django 4.1.7 on 2023-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_post_content_video_alter_post_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_video',
        ),
    ]
