# Generated by Django 4.1.7 on 2023-03-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_remove_post_content_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
