# Generated by Django 4.1.7 on 2023-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.FileField(blank=True, upload_to='posts/'),
        ),
    ]
