# Generated by Django 4.1.7 on 2023-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_alter_post_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
    ]
